In [2]:
import pandas as pd

In [3]:
path = 'D:/UZH/other/hasoc/new/rawdata/'

2021 datasets

In [4]:
en_train_21 = pd.read_csv(path + 'en_Hasoc2021_train.csv', header=0)
hi_train_21 = pd.read_csv(path + 'hi_Hasoc2021_train.csv', header=0)
mr_train_21 = pd.read_excel(path + 'mr_Hasoc2021_train.xlsx', header=0)

In [5]:
mr_train_21

            text_id                                               text task_1
0        hasoc_mr_1  ‡§≠‡§æ‡§∞‡§§ 15 ‡§ë‡§ó‡§∏‡•ç‡§ü 1947 ‡§≤‡§æ ‡§∏‡•ç‡§µ‡§§‡§Ç‡§§‡•ç‡§∞ ‡§ù‡§æ‡§≤‡§æ ‡§Ü‡§£‡§ø ‡§§‡•ç‡§Ø‡§æ‡§®‡§Ç...    NOT
1        hasoc_mr_2  ‡§∏‡•ç‡§µ‡§§ ‡§≤‡§æ ‡§π‡§µ‡§æ ‡§§‡§∏‡§æ ‡§¨‡§æ‡§á‡§ü ‡§ï‡§ø‡§Ç‡§µ‡§æ ‡§™‡•ç‡§∞‡§§‡§ø‡§ï‡•ç‡§∞‡§ø‡§Ø‡§æ ‡§ò‡•á‡§£‡•ç‡§Ø‡§æ‡§∏...    NOT
2        hasoc_mr_3  5 ‡§µ‡•ç‡§Ø‡§æ ‡§®‡§Ç‡§¨‡§∞‡§ö‡•Ä ‡§Ö‡§∞‡•ç‡§•‡§µ‡•ç‡§Ø‡§µ‡§∏‡•ç‡§•‡§æ ‡§Ü‡§π‡•á ‡§≠‡§æ‡§∞‡§§‡§æ‡§ö‡•Ä ‡§ú‡§ó‡§æ‡§§ 20...    NOT
3        hasoc_mr_4      ‡§ö‡•ç‡§Ø‡§æ‡§Ø‡§≤‡§æ ‡§Æ‡•ç‡§π‡§£‡§ú‡•á ‡§¶‡•Å‡§¨‡§à‡§ö‡§æ ‡§´‡•ã‡§® ‡§π‡•Ä ‡§™‡•Å‡§°‡•Ä‡§ö ‡§®‡§ø‡§ò‡§æ‡§≤‡•Ä ‡§ï‡•Ä.    HOF
4        hasoc_mr_5  ‡§π‡•ç‡§Ø‡§æ‡§≤‡§æ ‡§ñ‡§∞‡§Ç‡§§‡§∞ ‡§ï‡§ß‡•Ä‡§ö ‡§Ü‡§§ ‡§ü‡§æ‡§ï‡§≤‡§æ ‡§™‡§æ‡§π‡§ø‡§ú‡•á ‡§π‡•ã‡§§‡§æ. ‡§™‡•à‡§∏‡§æ ‡§Ü...    HOF
...             ...                                                ...    ...
1869  hasoc_mr_1870  ‡§Ü‡§†‡§µ‡•Ä‡§§ ‡§∂‡§ø‡§ï‡§§ ‡§Ö‡§∏‡§≤‡•á‡§≤‡•ç‡§Ø‡§æ ‡§∂‡§ø‡§∞‡•Ä‡§∑‡§ï‡•Å‡§Æ‡§æ‡§∞‡§®‡•á   ‡§π‡§ø‡§Ç‡§Æ‡§§ ‡§Ö‡§∏‡•á‡§≤ ...    NOT
1870  hasoc_mr_1871  ‡§§‡•Å‡§ù‡§æ ‡§™‡§ï‡•ç‡§∑ ‡§™‡§£ ‡§π‡§ø‡§Ç‡§¶‡•Å‡§§‡•ç‡§µ‡§µ‡§æ‡§¶‡•Ä‡§ö ‡§Ü‡§π‡•á ‡§®‡§æ? ‡§Æ‡§ó ‡§Ü‡§£‡§æ ‡§ï‡•Ä ‡§¨...    NOT
1871  hasoc_mr_1872  ‡§ö‡•ç‡§Ø‡§æ‡§Ø‡§≤‡§æ...‡•® ‡§Æ‡§π‡§ø‡§®‡•á ‡§Ü‡§ß‡•Ä ‡§π‡•á‡§ö ‡§≠‡§ø‡§ï‡§æ‡§∞‡§ö‡•ã‡§ü ‡§ï‡•á‡§Ç‡§¶‡•ç‡§∞‡§æ‡§ï‡§°‡•á ...    NOT
1872  hasoc_mr_1873  ‡•ß ‡§Æ‡•á ‡•ß‡•Ø‡•¨‡•¶ ‡§≤‡§æ ‡§∏‡•ç‡§•‡§æ‡§™‡§® ‡§ù‡§æ‡§≤‡•ç‡§Ø‡§æ‡§µ‡§∞ ‡§∞‡§æ‡§ú‡•ç‡§Ø‡§æ‡§ö‡•á ‡§∏‡•Å‡§∏‡§Ç‡§ò‡§ü‡§ø‡§§...    NOT
1873  hasoc_mr_1874                             ‡§ó‡•Ä‡§§ ‡§≠‡§ø‡§Æ‡§æ ‡§§‡•Å‡§ù‡•ç‡§Ø‡§æ‡§∏‡§æ‡§†‡•Ä ‚ù£Ô∏è    NOT

[1874 rows x 3 columns]

2020 datasets

In [6]:
en_train_20 = pd.read_excel(path + 'hasoc_2020_en_train_new.xlsx', header=0)
hi_train_20 = pd.read_excel(path + 'hasoc_2020_hi_train.xlsx', header=0)
de_train_20 = pd.read_excel(path + 'hasoc_2020_de_train_new.xlsx', header=0)
en_test_20 = pd.read_excel(path + 'hasoc_2020_en_test_new.xlsx', header=0)
hi_test_20 = pd.read_excel(path + 'hasoc_2020_hi_test.xlsx', header=0)
de_test_20 = pd.read_excel(path + 'hasoc_2020_de_test_new.xlsx', header=0)

In [7]:
en_train_20

,tweet_id,text,task1,task2,ID
0,1.123757e+18,"hate wen females hit ah nigga with tht bro üòÇüòÇ,...",HOF,PRFN,hasoc_2020_en_2574
1,1.123733e+18,RT @airjunebug: When you're from the Bay but y...,HOF,PRFN,hasoc_2020_en_3627
2,1.123734e+18,RT @DonaldJTrumpJr: Dear Democrats: The Americ...,NOT,NONE,hasoc_2020_en_3108
3,1.126951e+18,RT @SheLoveTimothy: He ain‚Äôt on drugs he just ...,HOF,PRFN,hasoc_2020_en_3986
4,1.126864e+18,RT @TavianJordan: Summer ‚Äò19 I‚Äôm coming for yo...,NOT,NONE,hasoc_2020_en_5152
...,...,...,...,...,...
3703,1.126887e+18,RT @FilthyArt_: TONIGHT TONIGHT TONIGHT \n\nCa...,NOT,NONE,hasoc_2020_en_109
3704,1.126826e+18,RT @abbn0rmal_: Eat my ass,HOF,PRFN,hasoc_2020_en_2345
3705,1.126880e+18,RT @FlyTPA: BREAKING NEWS: TPA is about to get...,NOT,NONE,hasoc_2020_en_1039
3706,1.130291e+18,RT @StarrThaRapper: It‚Äôs been a hr FUCK THAT G...,HOF,PRFN,hasoc_2020_en_2817
3707,1.126980e+18,You don't know who iam but i know youüòÑ,NOT,NONE,hasoc_2020_en_1585

2019 datasets

In [8]:
en_train_19 = pd.read_csv(path + 'english_dataset.tsv', header=0, delimiter='\t')
hi_train_19 = pd.read_csv(path + 'german_dataset.tsv', header=0, delimiter='\t')
de_train_19 = pd.read_csv(path + 'hindi_dataset.tsv', header=0, delimiter='\t')
en_test_19 = pd.read_csv(path + 'hasoc2019_en_test_2919.tsv', header=0, delimiter='\t')
hi_test_19 = pd.read_csv(path + 'hasoc2019_hi_test_gold_2919.tsv', header=0, delimiter='\t')
de_test_19 = pd.read_csv(path + 'hasoc_de_test_gold.tsv', header=0, delimiter='\t')

In [9]:
en_train_19

,text_id,text,task_1,task_2,task_3
0,hasoc_en_1,#DhoniKeepsTheGlove | WATCH: Sports Minister K...,NOT,NONE,NONE
1,hasoc_en_2,@politico No. We should remember very clearly ...,HOF,HATE,TIN
2,hasoc_en_3,@cricketworldcup Guess who would be the winner...,NOT,NONE,NONE
3,hasoc_en_4,Corbyn is too politically intellectual for #Bo...,NOT,NONE,NONE
4,hasoc_en_5,All the best to #TeamIndia for another swimmin...,NOT,NONE,NONE
...,...,...,...,...,...
5847,hasoc_en_5848,"@davidfrum @trueblueusa1 That's cute and all, ...",HOF,PRFN,UNT
5848,hasoc_en_5849,a recession issa comin' #maga #magamyass #fuck...,NOT,NONE,NONE
5849,hasoc_en_5850,#DoctorsFightBack Will 'The Mad n Irrational ...,HOF,OFFN,TIN
5850,hasoc_en_5851,#ShiningIndia #educatedindia or more like RUND...,HOF,OFFN,UNT
5851,hasoc_en_5852,Could this be our new Prime Minister? #Ric...,HOF,PRFN,UNT

In [10]:
en_train_21_t2 = pd.DataFrame(en_train_21, columns=['_id', 'text', 'task_2'])
en_train_21_t2.columns = ['id', 'text', 'task_2']
hi_train_21_t2 = pd.DataFrame(hi_train_21, columns=['tweet_id', 'text', 'task_2'])
hi_train_21_t2.columns = ['id', 'text', 'task_2']

In [11]:
en_train_20_t2 = pd.DataFrame(en_train_20, columns=['tweet_id', 'text', 'task2'])
en_train_20_t2.columns = ['id', 'text', 'task_2']
hi_train_20_t2 = pd.DataFrame(hi_train_20, columns=['tweet_id', 'text', 'task2'])
hi_train_20_t2.columns = ['id', 'text', 'task_2']
de_train_20_t2 = pd.DataFrame(de_train_20, columns=['tweet_id', 'text', 'task2'])
de_train_20_t2.columns = ['id', 'text', 'task_2']

en_test_20_t2 = pd.DataFrame(en_test_20, columns=['tweet_id', 'text', 'task2'])
en_test_20_t2.columns = ['id', 'text', 'task_2']
hi_test_20_t2 = pd.DataFrame(hi_test_20, columns=['tweet_id', 'text', 'task2'])
hi_test_20_t2.columns = ['id', 'text', 'task_2']
de_test_20_t2 = pd.DataFrame(de_test_20, columns=['tweet_id', 'text', 'task2'])
de_test_20_t2.columns = ['id', 'text', 'task_2']

In [12]:
en_train_19_t2 = pd.DataFrame(en_train_19, columns=['text_id', 'text', 'task_2'])
en_train_19_t2.columns = ['id', 'text', 'task_2']
hi_train_19_t2 = pd.DataFrame(hi_train_19, columns=['text_id', 'text', 'task_2'])
hi_train_19_t2.columns = ['id', 'text', 'task_2']
de_train_19_t2 = pd.DataFrame(de_train_19, columns=['text_id', 'text', 'task_2'])
de_train_19_t2.columns = ['id', 'text', 'task_2']

en_test_19_t2 = pd.DataFrame(en_test_19, columns=['text_id', 'text', 'task_2'])
en_test_19_t2.columns = ['id', 'text', 'task_2']
hi_test_19_t2 = pd.DataFrame(hi_test_19, columns=['text_id', 'text', 'task_2'])
hi_test_19_t2.columns = ['id', 'text', 'task_2']
de_test_19_t2 = pd.DataFrame(de_test_19, columns=['text_id', 'text', 'task_2'])
de_test_19_t2.columns = ['id', 'text', 'task_2']

In [13]:
t1_with_ge = [en_train_21_t2, hi_train_21_t2, 
en_train_20_t2, hi_train_20_t2, de_train_20_t2,
en_test_20_t2, hi_test_20_t2, de_test_20_t2,
en_train_19_t2, hi_train_19_t2, de_train_19_t2,
en_test_19_t2, hi_test_19_t2, de_test_19_t2]

In [14]:
t2_with_ge = pd.concat(t1_with_ge)

In [15]:
t2_with_ge.to_csv('t2_with_ge.tsv', sep='\t')

In [16]:
t2_without_ge = [en_train_21_t2, hi_train_21_t2, 
en_train_20_t2, hi_train_20_t2, 
en_test_20_t2, hi_test_20_t2, 
en_train_19_t2, hi_train_19_t2, 
en_test_19_t2, hi_test_19_t2]
t2_without_ge = pd.concat(t2_without_ge)

In [17]:
t2_without_ge.to_csv('t2_without_ge.tsv', sep='\t')

In [22]:
t2_only21 = [en_train_21_t2, hi_train_21_t2]
t2_only21 = pd.concat(t2_only21)

In [23]:
t2_only21.to_csv('t2_only21.tsv', sep='\t')

In [1]:
import pandas as pd

In [2]:
raw_data = pd.read_csv('t2_without_ge.tsv',sep='\t')

In [6]:
non = raw_data.loc[raw_data['task_2'] == 'NONE']
hate = raw_data.loc[raw_data['task_2'] == 'HATE']
offn = raw_data.loc[raw_data['task_2'] == 'OFFN']
prfn = raw_data.loc[raw_data['task_2'] == 'PRFN']

In [19]:
balanced_dataset=[non.sample(3351), hate.sample(3351), offn.sample(3351), prfn.sample(3351)]
balanced_dataset = pd.concat(balanced_dataset)
balanced_dataset.to_csv('balanced_dataset.tsv',sep='\t')

In [21]:
balanced_dataset.sample(10)

,Unnamed: 0,id,text,task_2
11099,2662,1.1301713944599512e+18,RT @tressabeu: people will apologize and go ba...,PRFN
7074,3231,hi_hasoc_2021_1981,@BiharTakChannel @khesariLY ‡§î‡§∞ ‡§π‡§æ‡§Å ‡§§‡•Å‡§Æ‡§®‡•á ‡§¨‡•ã‡§≤‡§æ ...,NONE
25381,1560,hasoc_de_1561,"Find ich irgendwie witzig, wenn ein schwuler G...",NONE
6712,2869,hi_hasoc_2021_5311,"60 ‡§ï‡§æ ‡§¶‡§∂‡§ï, ‡§´‡§º‡§ø‡§≤‡•ç‡§Æ ‚Äò‡§Æ‡•á‡§π‡§∞‡§¨‡§æ‡§®‚Äò ‡§ï‡§æ ‡§ó‡§æ‡§®‡§æ ‡§•‡§æ, ‚Äú‡§Æ‡•á‡§∞‡§æ ...",OFFN
15961,853,1.13006697306334e+18,RT @NiteLoops: Kim Kardashian and Kanye West n...,OFFN
11333,2896,1.1269222852255212e+18,Can‚Äôt let you fuck up the vibes,PRFN
15416,308,1.1237655346198404e+18,@CXG_80 damn üò≠,PRFN
189,189,60c5d6bf5659ea5e55df038d,False promises and utter lies @vijayrupanibjp ...,OFFN
20876,2907,hasoc_en_2908,"Highly shameful, for everything, and for all w...",HATE
1878,1878,60c5d6bf5659ea5e55df0054,@divya_16_ I lost two family members due to #C...,HATE